name: build ygopic-best

on:
  push:
    tags:
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
  
    - name: Cache
      uses: actions/cache@v4
      with:
        path: core-wasm/hd-arts
        key: ${{ runner.os }}-cache-hd-arts-${{ hashFiles('core-wasm/hd-arts/**') }}
        restore-keys: |
          ${{ runner.os }}-cache-hd-arts

    - name: prepare
      run: |
        sudo apt update
        sudo apt install openconnect

    - name: Connect VPN
      env:
        VPN_USER: ${{ secrets.VPN_USER }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        echo "$VPN_PASSWORD" | sudo openconnect \
          --user="$VPN_USER" \
          --passwd-on-stdin \
          --background \
          ${{ secrets.VPN_URL }}

    - name: build
      run: |
        cd core-wasm
        if [ -d "./hd-arts" ]; then
          cd hd-arts
          git pull
          cd ..
        else
          git clone ${{ secrets.PIC_URL }} --depth 1
        fi
        cargo run --release -- hd-arts/arts

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: card_data
        retention-days: 1
        path: ./core-wasm/card_data

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Create card_data
        run: |
          cd build
          gh release delete hash-latest --cleanup-tag -y || true
          gh release create hash-latest $(find . -type f) \
            --target "$GITHUB_SHA" \
            --title "card_data" \
            --notes "Latest build for ${{ github.ref_name }}" \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
